=== Common Tags

inspectIT OCE provides a map of common tag keys and values that are used when recording all metrics.
This features enables to "label" metrics collected with inspectIT OCE and share common information about a process or an environment where the process runs.
The map can be <<User Defined Tags Provider,extended or overwritten by the user>> when this is required.

Tags providers are responsible for extracting information from a specific source and provide a map of key value pairs that are then combined into the common tag context.
Each provider specifies a priority and if same tag keys are provided by two providers, then the tag value from a provider with higher priority will be used.

inspectIT OCE current supports the following tags providers:

[cols="2,2,1,1,1",options="header"]
|===
|Provider |Tags provided |Supports run-time updates |Enabled by default |Priority
|<<User Defined Tags>>
|-
|Yes
|No
|HIGH
|<<Environment Tags>>
|`service-name`, `host`, `host-address`
|Yes
|Yes
|LOW
|===

WARNING: Run-time updates currently only support changing of a tag value, but not adding or removing tags.

==== User Defined Tags

User defined tags can be added to the common tag context by defining the `inspectit.tags.extra` property.

.Setting the user defined tags using properties
[source,properties]
----
inspectit.tags.extra.region=us-west-1
inspectit.tags.extra.stage=preprod
----

.Setting the user defined tags using YAML file
[source,YAML]
----
inspectit:
  tags:
    extra:
      region: us-west-1
      stage: preprod
----

==== Environment Tags
The environment tags provider extends the common tag context by supplying information about the service name and a host.
The service name is resolved from the `inspectit.service-name` property, while host information is extracted using `InetAddress.getLocalHost()`.

NOTE: Note that on machines that have multiple network interfaces the `InetAddress.getLocalHost()` method might not provide desired values for host related tags.

[cols="5,1,3",options="header"]
.Properties related to the environment tags provider
|===
|Property |Default| Description
|```inspectit.tags.providers.environment.enabled```
|`true`
|Enables or disables the provider.
|```inspectit.tags.providers.environment.resolve-host-name```
|`true`
|If `false`, the tag `host` containing the resolved host name will not be provided.
|```inspectit.tags.providers.environment.resolve-host-address```
|`true`
|If `false`, the tag `host-address` containing the resolved host IP address will not be provided.
|===