{
 "title": "JVM Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service_name)" }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "system_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "system_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service_name=\"$service\"}",
     "legendFormat": "daemon",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_live{service_name=\"$service\"} - jvm_threads_daemon{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "non-deamon",
     "measurement": "jvm_threads_states",
     "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service\"} - jvm_threads_live{service_name=\"$service\"}",
     "legendFormat": "peak",
     "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "expr": "jvm_gc_live_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Live Data Size",
     "measurement": "jvm_gc_live_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Max Data Size",
     "expr": "jvm_gc_max_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max Data Size",
     "measurement": "jvm_gc_max_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Allocated Memory",
     "expr": "idelta(jvm_gc_memory_allocated{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Allocated Memory",
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "expr": "idelta(jvm_gc_memory_promoted{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Promoted Memory",
     "measurement": "jvm_gc_memory_promoted",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_states{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of major GC\"}[$__range])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "system_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "system_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service_name=\"$service\"}",
     "legendFormat": "daemon",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_live{service_name=\"$service\"} - jvm_threads_daemon{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "non-deamon",
     "measurement": "jvm_threads_states",
     "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service\"} - jvm_threads_live{service_name=\"$service\"}",
     "legendFormat": "peak",
     "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "expr": "jvm_gc_live_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Live Data Size",
     "measurement": "jvm_gc_live_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Max Data Size",
     "expr": "jvm_gc_max_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max Data Size",
     "measurement": "jvm_gc_max_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Allocated Memory",
     "expr": "idelta(jvm_gc_memory_allocated{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Allocated Memory",
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "expr": "idelta(jvm_gc_memory_promoted{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Promoted Memory",
     "measurement": "jvm_gc_memory_promoted",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_states{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of major GC\"}[$__range])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "system_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "system_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service_name=\"$service\"}",
     "legendFormat": "daemon",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_live{service_name=\"$service\"} - jvm_threads_daemon{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "non-deamon",
     "measurement": "jvm_threads_states",
     "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service\"} - jvm_threads_live{service_name=\"$service\"}",
     "legendFormat": "peak",
     "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "expr": "jvm_gc_live_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Live Data Size",
     "measurement": "jvm_gc_live_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Max Data Size",
     "expr": "jvm_gc_max_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max Data Size",
     "measurement": "jvm_gc_max_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Allocated Memory",
     "expr": "idelta(jvm_gc_memory_allocated{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Allocated Memory",
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "expr": "idelta(jvm_gc_memory_promoted{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Promoted Memory",
     "measurement": "jvm_gc_memory_promoted",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_states{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of major GC\"}[$__range])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "system_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "system_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service_name=\"$service\"}",
     "legendFormat": "daemon",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_live{service_name=\"$service\"} - jvm_threads_daemon{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "non-deamon",
     "measurement": "jvm_threads_states",
     "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service\"} - jvm_threads_live{service_name=\"$service\"}",
     "legendFormat": "peak",
     "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "expr": "jvm_gc_live_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Live Data Size",
     "measurement": "jvm_gc_live_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Max Data Size",
     "expr": "jvm_gc_max_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max Data Size",
     "measurement": "jvm_gc_max_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Allocated Memory",
     "expr": "idelta(jvm_gc_memory_allocated{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Allocated Memory",
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "expr": "idelta(jvm_gc_memory_promoted{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Promoted Memory",
     "measurement": "jvm_gc_memory_promoted",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 49 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_states{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of major GC\"}[$__range])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "system_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "system_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service_name=\"$service\"}",
     "legendFormat": "daemon",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_live{service_name=\"$service\"} - jvm_threads_daemon{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "non-deamon",
     "measurement": "jvm_threads_states",
     "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service\"} - jvm_threads_live{service_name=\"$service\"}",
     "legendFormat": "peak",
     "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "expr": "jvm_gc_live_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Live Data Size",
     "measurement": "jvm_gc_live_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Max Data Size",
     "expr": "jvm_gc_max_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max Data Size",
     "measurement": "jvm_gc_max_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Allocated Memory",
     "expr": "idelta(jvm_gc_memory_allocated{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Allocated Memory",
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "expr": "idelta(jvm_gc_memory_promoted{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Promoted Memory",
     "measurement": "jvm_gc_memory_promoted",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 63 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_states{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of major GC\"}[$__range])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "system_cpu_usage{service_name=\"$service\"}",
     "legendFormat": "system_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service_name=\"$service\"}",
     "legendFormat": "daemon",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_live{service_name=\"$service\"} - jvm_threads_daemon{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "non-deamon",
     "measurement": "jvm_threads_states",
     "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{service_name=\"$service\"} - jvm_threads_live{service_name=\"$service\"}",
     "legendFormat": "peak",
     "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service_name == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "expr": "jvm_gc_live_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Live Data Size",
     "measurement": "jvm_gc_live_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Max Data Size",
     "expr": "jvm_gc_max_data_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max Data Size",
     "measurement": "jvm_gc_max_data_size",
     "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service_name\" =~ /^$service$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Allocated Memory",
     "expr": "idelta(jvm_gc_memory_allocated{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Allocated Memory",
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "expr": "idelta(jvm_gc_memory_promoted{service_name=\"$service\"}[$__range])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "legendFormat": "Promoted Memory",
     "measurement": "jvm_gc_memory_promoted",
     "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 77 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$service\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 77 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "expr": "sum(jvm_memory_max{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "expr": "sum(jvm_memory_committed{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "used",
     "expr": "sum(jvm_memory_used{service_name=\"$service\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "jvm_threads_states{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service_name\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 77 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "idelta(jvm_gc_pause{service_name=\"$service\", action=\"end of major GC\"}[$__range])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service_name == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service_name\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 }, "content": "----" }
 ]
}