{
 "title": "inspectIT Agent Self-Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service_name)" }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "inspectit_self_instrumented_classes{service_name=\"$service\"} / jvm_classes_loaded{service_name=\"$service\"}",
     "query": "perc = () => {\ninstrumented = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"inspectit_self_instrumented_classes\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nloaded = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"jvm_classes_loaded\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nreturn join(tables:{instrumented:instrumented, loaded:loaded},on:[\"_time\"])\n|> map(fn:(r) => ({\n_time: r._time,\n_value: (r._value_instrumented / r._value_loaded),\n_measurement: \"perc-instrumented\"    }))\n|> last()\n}\n\nperc()"
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "legendFormat": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "expr": "inspectit_self_instrumentation_analysis_queue_size{service_name=\"$service\"}",
     "legendFormat": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "expr": "inspectit_self_instrumented_classes{service_name=\"$service\"}",
     "legendFormat": "# instrumented classes",
     "measurement": "inspectit_self_instrumentation_analysis_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (inspectit_self_instrumentation_analysis_queue_size{service_name=\"$service\"}/jvm_classes_loaded{service_name=\"$service\"})",
     "query": "perc = () => {\ninstrumented = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"inspectit_self_instrumentation_analysis_queue_size\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nloaded = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"jvm_classes_loaded\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nreturn join(tables:{instrumented:instrumented, loaded:loaded},on:[\"_time\"])\n|> map(fn:(r) => ({\n_time: r._time,\n_value: 1.0 - (r._value_instrumented / r._value_loaded),\n_measurement: \"progress\"    }))\n|> last()\n}\n\nperc()"
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "expr": "inspectit_self_instrumented_classes{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "instrumented classes",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "expr": "inspectit_self_instrumentation_analysis_queue_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "classes pending for analysis",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "loaded classes",
     "measurement": "inspectit_self_instrumentation_analysis_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "inspectit_self_instrumented_classes{service_name=\"$service\"} / jvm_classes_loaded{service_name=\"$service\"}",
     "query": "perc = () => {\ninstrumented = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"inspectit_self_instrumented_classes\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nloaded = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"jvm_classes_loaded\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nreturn join(tables:{instrumented:instrumented, loaded:loaded},on:[\"_time\"])\n|> map(fn:(r) => ({\n_time: r._time,\n_value: (r._value_instrumented / r._value_loaded),\n_measurement: \"perc-instrumented\"    }))\n|> last()\n}\n\nperc()"
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 8 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "legendFormat": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "expr": "inspectit_self_instrumentation_analysis_queue_size{service_name=\"$service\"}",
     "legendFormat": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "expr": "inspectit_self_instrumented_classes{service_name=\"$service\"}",
     "legendFormat": "# instrumented classes",
     "measurement": "inspectit_self_instrumentation_analysis_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (inspectit_self_instrumentation_analysis_queue_size{service_name=\"$service\"}/jvm_classes_loaded{service_name=\"$service\"})",
     "query": "perc = () => {\ninstrumented = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"inspectit_self_instrumentation_analysis_queue_size\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nloaded = from(bucket: \"telegraf\")\n|> range(start:-1h)\n|> filter(fn: (r) =>  \nr._measurement == \"jvm_classes_loaded\" AND  \nr.service_name == \"$service\" AND  \nr._field == \"gauge\")\n|> keep(columns: [\"_time\",\"_value\"])\n\n\nreturn join(tables:{instrumented:instrumented, loaded:loaded},on:[\"_time\"])\n|> map(fn:(r) => ({\n_time: r._time,\n_value: 1.0 - (r._value_instrumented / r._value_loaded),\n_measurement: \"progress\"    }))\n|> last()\n}\n\nperc()"
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "expr": "inspectit_self_instrumented_classes{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "instrumented classes",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "expr": "inspectit_self_instrumentation_analysis_queue_size{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "classes pending for analysis",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "expr": "jvm_classes_loaded{service_name=\"$service\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "loaded classes",
     "measurement": "inspectit_self_instrumentation_analysis_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}