== Self Monitoring

inspectIT OCE is able to monitor itself and report the time spent in components responsible for recording metrics and creating traces.
This way a user can have a clear view on what is the overhead introduced by running the inspectIT OCE agent.
When self monitoring is enabled, the agent will expose the `inspectit/self/duration` metric with the total execution time in microseconds.
The metric is split by the tag containing the component name.

.Exposed self-monitoring metric using the Prometheus exporter
```
# HELP inspectit_self_duration inspectIT OCE self-monitoring duration [μs]
# TYPE inspectit_self_duration counter
inspectit_self_duration{component_name="ClassLoaderMetricsRecorder",} 33814.0
inspectit_self_duration{component_name="DiskMetricsRecorder",} 38118.0
```

Self monitoring is disabled by default and can be enabled by setting the `inspectit.self-monitoring.enabled` property to `true`.

WARNING: Components responsible for internal management of inspectIT OCE are at the moment not reporting the time used for internal tasks. Please take the provided numbers only for a basic reference on overhead and don't assume they are 100% correct.
