== Self Monitoring

inspectIT OCE is able to monitor itself and report the time spent in components responsible for recording metrics and creating traces.
This way a user can have a clear view on what is the overhead introduced by running the inspectIT OCE agent.
When self monitoring is enabled, the agent will expose several metrics regarding its internal state and processes.
For example, the `inspectit/self/duration` metric gives the total execution time spent in the agent in microseconds.
All metrics include the configured <<Common Tags, common tags>>.
The metric is split by the tag containing the component name and also includes all common tags.

.Exposed self-monitoring metric using the Prometheus exporter
```
# HELP inspectit_self_duration inspectIT OCE self-monitoring duration [us]
# TYPE inspectit_self_duration counter
inspectit_self_duration{component_name="instrumentation-retransformation",host="myhostname",host_address="10.0.75.1",service_name="my-service",} 224652.0
inspectit_self_duration{component_name="class-discovery",host="myhostname",host_address="10.0.75.1",service_name="my-service",} 17145.0
inspectit_self_duration{component_name="instrumentation-analysis",host="myhostname",host_address="10.0.75.1",service_name="my-service",} 64426.0

# HELP inspectit_self_intrumentation_check_queue_size The number of pending classes inspectIT has to check if they require instrumentation updates [classes]
# TYPE inspectit_self_intrumentation_check_queue_size gauge
inspectit_self_intrumentation_check_queue_size{host="myhostname",host_address="10.0.75.1",service_name="my-service",} 3746.0

# HELP inspectit_self_instrumented_classes The number of currently by inspectIT instrumented classes [classes]
# TYPE inspectit_self_instrumented_classes gauge
inspectit_self_instrumented_classes{host="myhostname",host_address="10.0.75.1",service_name="my-service",} 2.0
```

Self monitoring is disabled by default and can be enabled by setting the `inspectit.self-monitoring.enabled` property to `true`.

WARNING: Components responsible for internal management of inspectIT OCE are at the moment not reporting the time used for internal tasks. Please take the provided numbers only for a basic reference on overhead and don't assume they are 100% correct.
