export const CHANGE_PASSWORD_STARTED = 'settings/PASSWORD_CHANGE_STARTED'
export const CHANGE_PASSWORD_FAILURE = 'settings/PASSWORD_CHANGE_FAILURE'
export const CHANGE_PASSWORD_SUCCESS = 'settings/PASSWORD_CHANGE_SUCCESS'

export const SEARCH_USER_FAILURE = 'settings/SEARCH_USER_FAILURE'
export const SEARCH_USER_SUCCESS = 'settings/SEARCH_USER_SUCCESS'