export const CHANGE_PASSWORD_STARTED = 'settings/PASSWORD_CHANGE_STARTED'
export const CHANGE_PASSWORD_FAILURE = 'settings/PASSWORD_CHANGE_FAILURE'
export const CHANGE_PASSWORD_SUCCESS = 'settings/PASSWORD_CHANGE_SUCCESS'

export const SEARCH_USER_STARTED = 'settings/SEARCH_USER_STARTED'
export const SEARCH_USER_FAILURE = 'settings/SEARCH_USER_FAILURE'
export const SEARCH_USER_SUCCESS = 'settings/SEARCH_USER_SUCCESS'

export const DELETE_USER_STARTED = 'settings/DELETE_USER_STARTED'
export const DELETE_USER_FAILURE = 'settings/DELETE_USER_FAILURE'
export const DELETE_USER_SUCCESS = 'settings/DELETE_USER_SUCCESS'

export const ADD_USER_STARTED = 'settings/ADD_USER_STARTED'
export const ADD_USER_FAILURE = 'settings/ADD_USER_FAILURE'
export const ADD_USER_SUCCESS = 'settings/ADD_USER_SUCCESS'