export const FETCH_USERS_STARTED = 'settings/FETCH_USERS_STARTED';
export const FETCH_USERS_FAILURE = 'settings/FETCH_USERS_FAILURE';
export const FETCH_USERS_SUCCESS = 'settings/FETCH_USERS_SUCCESS';

export const ADD_USER_STARTED = 'settings/ADD_USER_STARTED';
export const ADD_USER_FAILURE = 'settings/ADD_USER_FAILURE';
export const ADD_USER_SUCCESS = 'settings/ADD_USER_SUCCESS';

export const DELETE_USER_STARTED = 'settings/DELETE_USER_STARTED';
export const DELETE_USER_FAILURE = 'settings/DELETE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'settings/DELETE_USER_SUCCESS';

export const CHANGE_PASSWORD_STARTED = 'settings/CHANGE_PASSWORD_STARTED';
export const CHANGE_PASSWORD_FAILURE = 'settings/CHANGE_PASSWORD_FAILURE';
export const CHANGE_PASSWORD_SUCCESS = 'settings/CHANGE_PASSWORD_SUCCESS';
