=== Using OpenCensus Library with inspectIT Ocelot

If you plan to use the OpenCensus library in an application which will be instrumented later on with inspectIT Ocelot, some special rules do apply.
Following these rules will make sure that there are no run-time problems in your application.
Furthermore, a correct configuration will make it possible to combine metrics and traces that you manually collect using the OpenCensus instrumentation library with the ones collected by the inspectIT Ocelot agent.

. Make sure you are using the same version of OpenCensus as inspectIT Ocelot
+
The inspectIT Ocelot agent in version {inspectit-ocelot-version} internally uses OpenCensus in version {opencensus-version}.
Please adapt any OpenCensus dependency in your application to this version to avoid run-time conflicts.
+
```XML
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-api</artifactId>
    <version>{opencensus-version}</version>
</dependency>
```
. Set the JVM property `inspectit.publishOpenCensusToBootstrap` to `true`.
+
```
-Dinspectit.publishOpenCensusToBootstrap=true
```
Setting the above property to `true` tells inspectIT Ocelot that you plan to use the OpenCensus library in combination with the agent.
Note that this property must be specified as a JVM property with this exact name. The flexibility offered for all other config options do not apply here.
The inspectIT Ocelot agent will make sure that all OpenCensus classes are then loaded by the bootstrap class loader.
This ensures that OpenCensus implementation is shared between your manual instrumentation and the agent instrumentation, making the combing of data possible.

. Add the agent to the start of a JVM
+
You should install the agent at the <<Adding the Agent to the JVM,start of the JVM>>.
On success, the agent will print in its logs that it used the bootstrap loader for loading OpenCensus.
When attaching the agent during the run-time, OpenCensus will *not* be published to the bootstrap even if you configured `-Dinspectit.publishOpenCensusToBootstrap=true`.
If you anyhow do attach the agent, metrics and traces collected by inspectIT Ocelot will not be combined with the manual instrumentation.