{
 "title": "Beacons",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Beacon Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_beacons_received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg duration of all beacons",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "beacon_processor" ], "type": "tag" }
     ],
     "measurement": "inspectit_eum_self_beacons_processor",
     "query": "SELECT sum(\"duration_sum\")/sum(\"count\") FROM \"autogen\".\"inspectit_eum_self_beacons_processor\" WHERE $timeFilter GROUP BY \"beacon_processor\"",
     "select": [
      [
       { "params": [ "duration_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_beacon_processor",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "beacon_processor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_beacons_processor",
     "query": "SELECT sum(\"duration_sum\")/sum(\"count\")  FROM \"autogen\".\"inspectit_eum_self_beacons_processor\" WHERE $timeFilter GROUP BY time($interval), \"beacon_processor\" fill(none)",
     "select": [
      [
       { "params": [ "duration_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Beacon Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Duration",
     "groupBy": [
      { "params": [ "beacon_processor" ], "type": "tag" }
     ],
     "measurement": "inspectit_eum_self_beacons_processor",
     "query": "SELECT sum(\"duration_sum\")/sum(\"count\") FROM \"autogen\".\"inspectit_eum_self_beacons_processor\" WHERE $timeFilter GROUP BY \"beacon_processor\"",
     "select": [
      [
       { "params": [ "duration_sum" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}