{
 "title": "Trace Controller",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Received Traces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_traces_received",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"inspectit_eum_self_traces_received_duration\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Processing Times",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "inspectit_eum_self_traces_received",
     "query": "SELECT sum(\"duration_sum\")/sum(\"count\") FROM \"autogen\".\"inspectit_eum_self_traces_received\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "duration_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "All Traces",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_traces_received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Error Traces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_traces_received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "is_error", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Received Traces and Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Successful Traces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_traces_received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "is_error", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_traces_received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "is_error", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Average Duration of Traces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Avg Duration",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "inspectit_eum_self_traces_received",
     "query": "SELECT sum(\"duration_sum\")/sum(\"count\") FROM \"autogen\".\"inspectit_eum_self_traces_received\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spans per Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Span Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "inspectit_eum_self_traces_span_size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}