{
 "title": "HTTP Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service)" },
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   { "name": "path", "label": "Endpoint", "query": "label_values(http_path)" }
  ]
 },
 "panels": [
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "collapsed": true
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path)) >= 0\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "legendFormat": "{{http_path}}"
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0, \"http_url\", \"\", \"http_host\", \"http_path\")"
    },
    {
     "expr": "label_join((sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path)) >= 0\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0) * 0 , \"http_url\", \"\", \"http_host\", \"http_path\")"
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_host,http_path)\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_host,http_path)) >= 0",
     "legendFormat": "{{http_host}}{{http_path}}"
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  }
 ]
}