# used by:
# - HttpUrlConnectionContextPropagationTest
# - ServletApiContextPropagationTest
# - JmsApiContextPropagationTest
inspectit:
  instrumentation:
    data:
      up_propagated:
        up-propagation: GLOBAL
        down-propagation: JVM_LOCAL
      up_propagated2:
        up-propagation: GLOBAL
        down-propagation: JVM_LOCAL
      down_propagated:
        down-propagation: GLOBAL
      down_propagated_2:
        down-propagation: GLOBAL
      something:
        down-propagation: JVM_LOCAL
