export const UNSAVED_RULE_CONTENTS_CHANGED = 'alerting/UNSAVED_RULE_CONTENTS_CHANGED';
export const ALERTING_RULES_GROUPING_CONFIG_CHANGED = 'alerting/ALERTING_RULES_GROUPING_CONFIG_CHANGED';
export const UNSAVED_HANDLER_CONTENTS_CHANGED = 'alerting/UNSAVED_HANDLER_CONTENTS_CHANGED';
