export const FETCH_STATUS_STARTED = 'agentStatus/FETCH_STATUS_STARTED';
export const FETCH_STATUS_FAILURE = 'agentStatus/FETCH_STATUS_FAILURE';
export const FETCH_STATUS_SUCCESS = 'agentStatus/FETCH_STATUS_SUCCESS';

export const CLEAR_STATUS_STARTED = 'agentStatus/CLEAR_STATUS_STARTED';
export const CLEAR_STATUS_FAILURE = 'agentStatus/CLEAR_STATUS_FAILURE';
export const CLEAR_STATUS_SUCCESS = 'agentStatus/CLEAR_STATUS_SUCCESS';
