=== Using OpenCensus Library with inspectIT OCE

If you plan to use the OpenCensus library in an application which will be instrumented later on with inspectIT OCE, some special rules do apply.
Following these rules will make sure that there are no run-time problems in your application.
Furthermore, a correct configuration will make it possible to combine metrics and traces that you manually collect using the OpenCensus instrumentation library with the ones collected by the inspectIT OCE agent.

. Make sure you are using the same version of OpenCensus as inspectIT OCE
+
The inspectIT OCE agent in version {inspectit-oce-version} internally uses OpenCensus in version {opencensus-version}.
Please adapt any OpenCensus dependency in your application to this version to avoid run-time conflicts.
+
```XML
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-api</artifactId>
    <version>0.18.0</version>
</dependency>
```
. Set the `inspectit.publish-opencensus-to-bootstrap` property to `true`
+
Setting the above property to `true` tells inspectIT OCE that you plan to use the OpenCensus library in combination with the agent.
The inspectIT OCE agent will make sure that all OpenCensus classes are then loaded by the bootstrap class loader.
This ensures that OpenCensus implementation is shared between your manual instrumentation and the agent instrumentation, making the combing of data possible.
. Add the agent to the start of a JVM
+
You should install the agent at the <<Adding the Agent to the JVM,start of the JVM>>.
You should avoid attaching the agent during the run-time, as at this point it's already too late for the inspectIT OCE agent to perform needed setup described in the previous point.
If you anyhow do attach the agent, metrics and traces collected by inspectIT OCE will not be combined with the manual instrumentation.
In such case you can also omit setting the `inspectit.publish-opencensus-to-bootstrap` property to `true`.