{
 "title": "EUM  Server Summary",
 "description": "End-User-Monitorig information collected by inspectIT.",
 "tags": [ "inspectit" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "URL", "query": "label_values(URL)" },
   { "name": "COUNTRY_CODE", "label": "Country", "query": "label_values(COUNTRY_CODE)" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "valueName": "avg",
   "targets": [
    {
     "expr": "load_time_SUM{URL=~\"$URL\"} / load_time_COUNT{URL=~\"$URL\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{COUNTRY_CODE}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "SUM(page_ready_time_COUNT) by (URL)",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "legendFormat": "{{URL}}",
     "measurement": "eum_browser_pageload",
     "query": "SHOW TAG VALUES FROM \"eum_browser_pageload\" WITH KEY = \"url\"",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Speedindex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Avg. Speedindex of $URL",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(speedindex_SUM{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})/sum(speedindex_COUNT{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Speedindex",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "speedindex",
     "expr": "sum(speedindex_SUM{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})/sum(speedindex_COUNT{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})",
     "legendFormat": "Speedindex",
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Navigation Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Avg. Load Time of $URL",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(load_time_SUM{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"}) / sum(load_time_COUNT{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(load_time_SUM{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"}) / sum(load_time_COUNT{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "Load Time",
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"loadEventEnd\") AS \"Load Event End\" , mean(\"firstpaint\") AS \"First Paint\", mean(\"responseStart\") AS \"Response Start\" FROM \"eum_browser_pageload\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "loadEventEnd" ], "type": "field" }
      ],
      [
       { "params": [ "firstpaint" ], "type": "field" }
      ],
      [
       { "params": [ "responseStart" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "sum(page_ready_time_SUM{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"}) / sum(page_ready_time_COUNT{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})",
     "legendFormat": "Page Ready Time"
    },
    {
     "expr": "sum(visual_ready_time_SUM{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"}) / sum(visual_ready_time_COUNT{URL=~\"$URL\", COUNTRY_CODE=~\"$COUNTRY_CODE\"})",
     "legendFormat": "Visual Ready Time"
    }
   ]
  }
 ]
}