== Tracing

This section provides all the information on trace collection with inspectIT Ocelot.

[IMPORTANT]
.Master switch for tracing
====
The inspectIT Ocelot configuration has a master switch for tracing, which can be used to completly disable anything that has to do with trace collection and exporting.
Tracing in the agent can be completely disabled by setting the `inspectit.tracing.enabled` property to `false`.
This way any default inspectIT setting or anything else defined for trace collection will be overruled.
If used, the switch makes sure that the inspectIT Ocelot agent:

. disables all trace exporters
. removes tracing from all <<Rules,instrumentation rules>>
====

It is possible to globally regulate the number of traces generated through https://opencensus.io/tracing/sampling/[sampling].
You can configure the probability with which a trace ends up being collected via `inspectit.tracing.sampleProbability`.
E.g. setting the value to `0.1` will result in only 10% of all traces being collected.
By default, the sample probability is 100%. Note that this global setting only acts as a default value and can be overridden by <<Collecting Traces,individual rules>>.

include::tracing-exporters.adoc[]