=== Trace Exporters

Metrics exporters are responsible for passing the recorded tracing data to a corresponding storage.
inspectIT Ocelot currently supports the following OpenCensus trace exporters:

* <<ZipKin Exporter,ZipKin>> (https://zipkin.io/[homepage])
* <<Jaeger Exporter, Jaeger>> (https://www.jaegertracing.io/[homepage])

==== ZipKin Exporter

The ZipKin exporter exports Traces in ZipKin v2 format to a ZipKin server or other compatible servers.
It can be enabled and disabled via the `inspectit.exporters.tracing.zipkin.enabled` property. By default, the ZipKin exporter is enabled. It however does not have an URL configured. The exporter will start up as soon as you define the `inspectit.exporters.tracing.zipkin.url` property.

For example, when adding the following property to your `-javaagent` options, traces will be sent to a zipkin server running on your localhost with the default port:

```
-Dinspectit.exporters.tracing.zipkin.url=http://127.0.0.1:9411/api/v2/spans
```

When sending spans, ZipKin expects you to give a name of the service where the spans have been recorded. This name can be set using the `inspectit.exporters.tracing.zipkin.service-name` property. This property defaults to `inspectit.service-name`.


==== Jaeger Exporter

The Jeager exports works exactly the same way as the <<ZipKin Exporter>>.
The corresponding properties are the following:

* `inspectit.exporters.tracing.jaeger.enabled`: enables / disables teh Jaeger exporter
* `inspectit.exporters.tracing.jaeger.url`: defines the URL where the spans will be pushed
* `inspectit.exporters.tracing.jaeger.service-name`: defines the service name under which the spans will be published

By default, the Jaeger exporter is enabled but has no URL configured.
The service name defaults to `inspectit.service-name`.

To make inspectIT Ocelot pus hthe spans to a Jaeger server running on the same machine as the agent, the following JVM property can be used:

```
-Dinspectit.exporters.tracing.jeager.url=http://127.0.0.1:14268/api/traces
```