package rocks.inspectit.ocelot.bootstrap.instrumentation;

/**
 * Interface implemented by all generic actions which are generated by the GenericActionGenerator.
 * The generated class use the template GenericActionTemplate or the GenericVoidActionTemplate.
 */
public interface IGenericAction {

    /**
     * This interface is implemented by all actions which are generated via CodeInjection.
     *
     * @param instrumentedMethodArgs the arguments passed to the method for which the action is executed
     * @param thiz                   the "this" instance of the invoked method, null if the invoked method is static
     * @param returnValue            the return value returned by the target method, if this action is executed at the end and no exception was thrown
     * @param thrown                 the exception thrown by the instrumented method, null otherwise
     * @param additionalArgs         additional arguments, such as constants or values from the data cloud which are passed to this action
     * @return the collected datum or null if nothing was collected
     */
    Object execute(Object[] instrumentedMethodArgs, Object thiz, Object returnValue, Throwable thrown, Object[] additionalArgs);

}
