{
 "title": "JVM Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "{\"find\": \"terms\", \"field\": \"tag.service_name\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "process",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:system_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "non-daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_live.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_live AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_daemon.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_daemon AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "peak",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_peak.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_peak AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "metrics": [
      {
       "field": "jvm_gc_live_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_live_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Max Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_max_data_size",
     "metrics": [
      {
       "field": "jvm_gc_max_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_max_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "process_cpu_usage",
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_loaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_loaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BLOCKED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:BLOCKED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NEW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:NEW",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "RUNNABLE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:RUNNABLE",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TERMINATED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TERMINATED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TIMED_WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TIMED_WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Minor GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of minor GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of minor GC" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Major GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of major GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of major GC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_unloaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_unloaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "process",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:system_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "non-daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_live.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_live AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_daemon.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_daemon AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "peak",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_peak.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_peak AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "metrics": [
      {
       "field": "jvm_gc_live_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_live_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Max Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_max_data_size",
     "metrics": [
      {
       "field": "jvm_gc_max_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_max_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "process_cpu_usage",
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_loaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_loaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BLOCKED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:BLOCKED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NEW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:NEW",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "RUNNABLE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:RUNNABLE",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TERMINATED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TERMINATED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TIMED_WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TIMED_WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Minor GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of minor GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of minor GC" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Major GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of major GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of major GC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_unloaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_unloaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "process",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:system_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "non-daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_live.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_live AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_daemon.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_daemon AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "peak",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_peak.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_peak AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "metrics": [
      {
       "field": "jvm_gc_live_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_live_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Max Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_max_data_size",
     "metrics": [
      {
       "field": "jvm_gc_max_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_max_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "process_cpu_usage",
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_loaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_loaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BLOCKED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:BLOCKED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NEW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:NEW",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "RUNNABLE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:RUNNABLE",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TERMINATED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TERMINATED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TIMED_WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TIMED_WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Minor GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of minor GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of minor GC" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Major GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of major GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of major GC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_unloaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_unloaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "process",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:system_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "non-daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_live.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_live AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_daemon.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_daemon AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "peak",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_peak.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_peak AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "metrics": [
      {
       "field": "jvm_gc_live_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_live_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Max Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_max_data_size",
     "metrics": [
      {
       "field": "jvm_gc_max_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_max_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 49 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "process_cpu_usage",
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_loaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_loaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BLOCKED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:BLOCKED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NEW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:NEW",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "RUNNABLE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:RUNNABLE",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TERMINATED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TERMINATED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TIMED_WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TIMED_WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Minor GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of minor GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of minor GC" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Major GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of major GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of major GC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_unloaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_unloaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "process",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:system_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "non-daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_live.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_live AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_daemon.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_daemon AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "peak",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_peak.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_peak AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "metrics": [
      {
       "field": "jvm_gc_live_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_live_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Max Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_max_data_size",
     "metrics": [
      {
       "field": "jvm_gc_max_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_max_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 63 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "process_cpu_usage",
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_loaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_loaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BLOCKED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:BLOCKED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NEW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:NEW",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "RUNNABLE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:RUNNABLE",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TERMINATED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TERMINATED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TIMED_WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TIMED_WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Minor GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of minor GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of minor GC" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Major GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of major GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of major GC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_unloaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_unloaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }, "content": "----" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "process",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:system_cpu_usage AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:heap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Live Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "non-daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_live.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_live AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "daemon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_daemon.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_daemon AND tag.service_name:$service",
     "timeField": "@timestamp"
    },
    {
     "alias": "peak",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_threads_peak.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_peak AND tag.service_name:$service",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage Collection Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Live Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "metrics": [
      {
       "field": "jvm_gc_live_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_live_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Max Data Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_max_data_size",
     "metrics": [
      {
       "field": "jvm_gc_max_data_size.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_max_data_size AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 77 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "measurement": "process_cpu_usage",
     "metrics": [
      {
       "field": "process_cpu_usage.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "measurement_name:process_cpu_usage AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 77 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_loaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_loaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "metrics": [
      {
       "field": "jvm_memory_max.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_max AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "metrics": [
      {
       "field": "jvm_memory_committed.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_committed AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "metrics": [
      {
       "field": "jvm_memory_used.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "measurement_name:jvm_memory_used AND tag.service_name:$service AND tag.area:nonheap",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# Threads by States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BLOCKED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:BLOCKED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NEW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:NEW",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "RUNNABLE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:RUNNABLE",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TERMINATED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TERMINATED",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "TIMED_WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:TIMED_WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WAITING",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "metrics": [
      {
       "field": "jvm_threads_states.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_threads_states AND tag.service_name:$service AND tag.state:WAITING",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Garbage Collection Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 77 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Minor GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of minor GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of minor GC" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Major GC",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "measurement": "jvm_gc_pause",
     "metrics": [
      {
       "field": "jvm_gc_pause.counter",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_gc_pause AND tag.service_name:$service AND tag.action:\"end of major GC\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end of major GC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unloaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "jvm_classes_unloaded.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "measurement_name:jvm_classes_unloaded AND tag.service_name:$service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 }, "content": "----" }
 ]
}