name: Automatic Security Check Configuration-Server

on:
  schedule:
    - cron: "0 8 1,15 * *" # At 08:00 on day-of-month 1 and 15

jobs:
  security-check:
    name: Security Check Configuration-Server
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-slim
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build
        run: ./gradlew :inspectit-ocelot-configurationserver:bootJarWithFrontend
      # the action has not been updated a while, but it always uses the latest plugin version
      - name: Run DependencyCheck plugin
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        continue-on-error: true
        with:
          project: inspectIT/inspectit-ocelot-configuration-server
          path: 'components/inspectit-ocelot-configurationserver'
          format: 'HTML'
          args: >
            --disableAssembly
            --disableNodeAudit
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --nvdApiDelay 10000
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-ocelot-agent
          path: ${{ github.workspace }}/reports
      - name: Send Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*Ocelot-Configuration-Server Dependency-Check Report*: ${{ steps.depcheck.outcome }}\nPlease check the report here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      # if DependencyCheck failed, the job should also fail, but only after the results were uploaded
      - name: Validate DependencyCheck outcome
        if: ${{ steps.depcheck.outcome == 'failure' }}
        run: |
          echo "DependencyCheck failed"
          exit 1
