Name: Push Docker images manually

# Use with care!!!
# Use this workflow to push new docker images to the latest version manually
# Same workflow as in release.yml

on:
  workflow_dispatch:

jobs:
  fetch_latest_tag:
    name: 'Fetch latest tag'
    runs-on: ubuntu-latest
    environment: release
    outputs:
      latest_tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history so tags are available
      - name: Get latest Git tag
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag is $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

  build:
    needs: fetch_latest_tag
    name: 'Build'
    runs-on: ubuntu-latest
    environment: release
    env:
      LATEST_TAG: ${{ needs.fetch_latest_tag.outputs.latest_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build artifacts
        run: ./gradlew assemble bootJarWithFrontend -PbuildVersion=$LATEST_TAG
        # copy jars into Docker folders
      - name: Prepare Docker artifacts
        run: ./gradlew :inspectit-ocelot-agent:copyAgentJar :inspectit-ocelot-configurationserver:copyServerJar
      - name: Upload Docker artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-artifacts
          path: |
            inspectit-ocelot-agent/docker/inspectit-ocelot-agent.jar
            components/inspectit-ocelot-configurationserver/docker/inspectit-ocelot-configurationserver.jar

  # Build the Docker images for multiple platforms and prepare for publishing
  # Check out: https://github.com/docker/build-push-action
  # And: https://docs.docker.com/build/ci/github-actions/multi-platform/
  build_docker_images:
    name: "Build Docker Images"
    runs-on: ubuntu-latest
    needs: build
    environment: release
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so tags are available
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Docker artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-artifacts
          path: ./docker-artifacts
      - name: Move artifacts into Docker folders
        run: |
          mv docker-artifacts/inspectit-ocelot-agent/docker/inspectit-ocelot-agent.jar inspectit-ocelot-agent/docker
          mv docker-artifacts/components/inspectit-ocelot-configurationserver/docker/inspectit-ocelot-configurationserver.jar components/inspectit-ocelot-configurationserver/docker

      - name: Build and push agent
        id: build-agent
        uses: docker/build-push-action@v6
        with:
          context: inspectit-ocelot-agent/docker
          file: inspectit-ocelot-agent/docker/Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=inspectit/inspectit-ocelot-agent,push-by-digest=true,name-canonical=true,push=true
      - name: Export digest agent
        run: |
          mkdir -p ${{ runner.temp }}/digests-agent
          digest="${{ steps.build-agent.outputs.digest }}"
          touch "${{ runner.temp }}/digests-agent/${digest#sha256:}"
      - name: Upload digest agent
        uses: actions/upload-artifact@v4
        with:
          name: digests-agent-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests-agent/*
          if-no-files-found: error
          retention-days: 1

      - name: Build and push configurationserver
        id: build-configurationserver
        uses: docker/build-push-action@v6
        with:
          context: components/inspectit-ocelot-configurationserver/docker
          file: components/inspectit-ocelot-configurationserver/docker/Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=inspectit/inspectit-ocelot-configurationserver,push-by-digest=true,name-canonical=true,push=true
      - name: Export digest configurationserver
        run: |
          mkdir -p ${{ runner.temp }}/digests-configurationserver
          digest="${{ steps.build-configurationserver.outputs.digest }}"
          touch "${{ runner.temp }}/digests-configurationserver/${digest#sha256:}"
      - name: Upload digest configurationserver
        uses: actions/upload-artifact@v4
        with:
          name: digests-configurationserver-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests-configurationserver/*
          if-no-files-found: error
          retention-days: 1

  # Merge the prepared Docker images and publish to DockerHub
  merge_and_publish_docker_images:
    name: "Merge and Publish Docker Images"
    runs-on: ubuntu-latest
    needs: build_docker_images
    environment: release
    env:
      LATEST_TAG: ${{ needs.fetch_latest_tag.outputs.latest_tag }}
    steps:
      - name: Download digests agent
        uses: actions/download-artifact@v4
        with:
          pattern: digests-agent-*
          path: ${{ runner.temp }}/digests-agent
          merge-multiple: true
      - name: Download digests configurationserver
        uses: actions/download-artifact@v4
        with:
          pattern: digests-configurationserver-*
          path: ${{ runner.temp }}/digests-configurationserver
          merge-multiple: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # publish agent
      - name: Docker meta agent
        id: meta-agent
        uses: docker/metadata-action@v5
        with:
          images: inspectit/inspectit-ocelot-agent
          tags: |
            type=raw,value=${{ env.LATEST_TAG }}
            type=raw,value=latest
      - name: Push agent
        working-directory: ${{ runner.temp }}/digests-agent
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf 'inspectit/inspectit-ocelot-agent@sha256:%s ' *)
      - name: Inspect manifest agent
        run: |
          docker buildx imagetools inspect inspectit/inspectit-ocelot-agent:$LATEST_TAG

        # publish configuration-server
      - name: Docker meta configurationserver
        id: meta-configurationserver
        uses: docker/metadata-action@v5
        with:
          images: inspectit/inspectit-ocelot-configurationserver
          tags: |
            type=raw,value=${{ env.LATEST_TAG }}
            type=raw,value=latest
      - name: Push configurationserver
        working-directory: ${{ runner.temp }}/digests-configurationserver
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf 'inspectit/inspectit-ocelot-configurationserver@sha256:%s ' *)
      - name: Inspect manifest configurationserver
        run: |
          docker buildx imagetools inspect inspectit/inspectit-ocelot-configurationserver:$LATEST_TAG
