export const FETCH_MAPPINGS_STARTED = 'mappings/FETCH_MAPPINGS_STARTED';
export const FETCH_MAPPINGS_FAILURE = 'mappings/FETCH_MAPPINGS_FAILURE';
export const FETCH_MAPPINGS_SUCCESS = 'mappings/FETCH_MAPPINGS_SUCCESS';

export const PUT_MAPPINGS_STARTED = 'mappings/PUT_MAPPINGS_STARTED';
export const PUT_MAPPINGS_FAILURE = 'mappings/PUT_MAPPINGS_FAILURE';
export const PUT_MAPPINGS_SUCCESS = 'mappings/PUT_MAPPINGS_SUCCESS';

export const PUT_MAPPING_STARTED = 'mappings/PUT_MAPPING_STARTED';
export const PUT_MAPPING_FAILURE = 'mappings/PUT_MAPPING_FAILURE';
export const PUT_MAPPING_SUCCESS = 'mappings/PUT_MAPPING_SUCCESS';

export const DELETE_MAPPING_STARTED = 'mappings/DELETE_MAPPING_STARTED';
export const DELETE_MAPPING_FAILURE = 'mappings/DELETE_MAPPING_FAILURE';
export const DELETE_MAPPING_SUCCESS = 'mappings/DELETE_MAPPING_SUCCESS';

export const FETCH_MAPPINGS_SOURCE_BRANCH_STARTED = 'mappings/FETCH_MAPPINGS_SOURCE_BRANCH_STARTED';
export const FETCH_MAPPINGS_SOURCE_BRANCH_SUCCESS = 'mappings/FETCH_MAPPINGS_SOURCE_BRANCH_SUCCESS';
export const FETCH_MAPPINGS_SOURCE_BRANCH_FAILURE = 'mappings/FETCH_MAPPINGS_SOURCE_BRANCH_FAILURE';
export const PUT_MAPPINGS_SOURCE_BRANCH_STARTED = 'mappings/FETCH_MAPPINGS_SOURCE_BRANCH_STARTED';
export const PUT_MAPPINGS_SOURCE_BRANCH_SUCCESS = 'mappings/PUT_MAPPINGS_SOURCE_BRANCH_SUCCESS';
export const PUT_MAPPINGS_SOURCE_BRANCH_FAILURE = 'mappings/PUT_MAPPINGS_SOURCE_BRANCH_FAILURE';

export const FETCH_VERSIONS_STARTED = 'mappings/FETCH_VERSIONS_STARTED';
export const FETCH_VERSIONS_FAILURE = 'mappings/FETCH_VERSIONS_FAILURE';
export const FETCH_VERSIONS_SUCCESS = 'mappings/FETCH_VERSIONS_SUCCESS';

export const SELECT_VERSION = 'mappings/SELECT_VERSION';
export const TOGGLE_HISTORY_VIEW = 'configuration/TOGGLE_HISTORY_VIEW';
