export const FETCH_MAPPINGS_STARTED = 'mappings/FETCH_MAPPINGS_STARTED';
export const FETCH_MAPPINGS_FAILURE = 'mappings/FETCH_MAPPINGS_FAILURE';
export const FETCH_MAPPINGS_SUCCESS = 'mappings/FETCH_MAPPINGS_SUCCESS';

export const PUT_MAPPINGS_STARTED = 'mappings/PUT_MAPPINGS_STARTED';
export const PUT_MAPPINGS_FAILURE = 'mappings/PUT_MAPPINGS_FAILURE';
export const PUT_MAPPINGS_SUCCESS = 'mappings/PUT_MAPPINGS_SUCCESS';

export const PUT_MAPPING_STARTED = 'mappings/PUT_MAPPING_STARTED';
export const PUT_MAPPING_FAILURE = 'mappings/PUT_MAPPING_FAILURE';
export const PUT_MAPPING_SUCCESS = 'mappings/PUT_MAPPING_SUCCESS';

export const DELETE_MAPPING_STARTED = 'mappings/DELETE_MAPPING_STARTED';
export const DELETE_MAPPING_FAILURE = 'mappings/DELETE_MAPPING_FAILURE';
export const DELETE_MAPPING_SUCCESS = 'mappings/DELETE_MAPPING_SUCCESS';
