export const FETCH_MAPPINGS_STARTED = 'mappings/FETCH_MAPPINGS_STARTED';
export const FETCH_MAPPINGS_FAILURE = 'mappings/FETCH_MAPPINGS_FAILURE';
export const FETCH_MAPPINGS_SUCCESS = 'mappings/FETCH_MAPPINGS_SUCCESS';

export const PUT_MAPPINGS_STARTED = 'mappings/PUT_MAPPINGS_STARTED';
export const PUT_MAPPINGS_FAILURE = 'mappings/PUT_MAPPINGS_FAILURE';
export const PUT_MAPPINGS_SUCCESS = 'mappings/PUT_MAPPINGS_SUCCESS';

export const UPDATE_MAPPING_IN_COPY = 'mappings/UPDATE_MAPPING_IN_COPY' ;
